name: Docs Check
description: Verify required documentation files exist in a repository
inputs:
  path:
    description: Path to repository root or subdirectory
    required: false
    default: .
  files:
    description: Comma-separated list of required files
    required: false
    default: README.md,AGENTS.md,SPEC.md,TODO.md
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        set -euo pipefail
        PATH_INPUT="${{ inputs.path }}"
        FILES_INPUT="${{ inputs.files }}"
        IFS=',' read -r -a REQ <<< "$FILES_INPUT"
        missing=()
        for f in "${REQ[@]}"; do
          ftrim=$(echo "$f" | xargs)
          if [[ ! -f "$PATH_INPUT/$ftrim" ]]; then
            missing+=("$ftrim")
          fi
        done
        if [[ ${#missing[@]} -gt 0 ]]; then
          echo "Missing required docs: ${missing[*]}" >&2
          exit 1
        fi
        echo "All required docs present in $PATH_INPUT: $FILES_INPUT"
