# Example GitHub Actions workflow to verify required docs exist.
# Usage: copy this file into your repo at .github/workflows/docs-check.yml

name: Docs Check

on:
  pull_request:
    branches: [ main ]

jobs:
  docs-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check required docs
        uses: PaulCapestany/ecosystem/.github/actions/docs-check@v1
        with:
          path: .
          files: README.md,AGENTS.md,SPEC.md,TODO.md
