# Example GitHub Actions workflow to verify required docs exist.
# Usage: copy this file into your repo at .github/workflows/docs-check.yml

name: Docs Check

on:
  pull_request:
    branches: [ main ]

jobs:
  docs-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check required docs
        run: |
          if [ ! -f scripts/check-required-docs.sh ]; then
            echo "scripts/check-required-docs.sh not found; skipping (copy from ecosystem repo if desired)."
            exit 0
          fi
          bash scripts/check-required-docs.sh .

