name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: |
          if [ -f package-lock.json ] || [ -f yarn.lock ]; then
            npm install
          elif [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
      - name: Run tests
        run: |
          if [ -f package.json ]; then
            npm test
          elif ls **/*_test.py 1> /dev/null 2>&1; then
            pytest
          else
            echo "No tests configured"
          fi
